### PR TITLE
Adds the G.U.M.P. concert to the list of events

### PR DESCRIPTION
**Pull request by pvtorrente**
Adds the G.U.M.P. with NappyNappa concert to the list of events. I will find some pictures to add to this later.

### CODE REVIEW

**Comment by renandincer** [comment]
awesome! :+1:

**Comment by renandincer** [comment]
@pvtorrente did you intend to open this pull request to the master branch as opposed to the summer-schedule branch?

**Comment by pvtorrente** [comment]
@renandincer yeah I meant to pull request to the master branch. Sorry about that.

**Comment by renandincer** [comment]
@pvtorrente no problem! I'll merge summer-schedule to master.

**Pull request merged**
