### PR TITLE
Updates the events

### PR DESCRIPTION
**Pull request by pvtorrente**
Adds all of the new events we have been hosting and planning on hosting for the spring semester.

### CODE REVIEW

**Comment by renandincer** [comment]
You're now an admin. Feel free to merge your own PRs.

**Comment by renandincer** [comment]
That being said, getting feedback is always good. :+1:

**Comment by pvtorrente** [comment]
Thank you!

**Comment by renandincer** [comment]
haha watch your dates! https://github.com/wjrh/wjrh.org/pull/22 @pvtorrente

**Pull request merged**
